project:
  type: website

website:
  title: "Imperial Mathematics Teaching Seminar"
  navbar:
    right:
      - talks.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto


