---
title: "Talks"
---

## Upcoming Talks 

:::{.callout-note title="Next Talk"}

**Speaker:** [Beth Hocking](https://www.imperial.ac.uk/education-research/about/students/), Centre for Higher Education Research and Scholarship, Imperial College London.

**Title:** Measuring potential

**Abstract:**  Patterns of participation in high tariff undergraduate higher education in England suggest difficulties in widening participation, particularly in STEM. Elite institutions, with high numbers of applicants per place, face the challenge of finding fair and practical approaches to selection. This involves the consideration of a range of philosophical, legal, strategic and cost issues.
 
Institutional and discipline-specific responses to this evolving challenge vary. Some favour ‘mechanised’ approaches to assessing potential and disadvantage, which prioritise admissions tests and widening participation flags. Both are cost effective and appear objective but hide complexity and interaction. Hence, over-reliance can result in distorted patterns of participation and affect course culture.
 
In this talk, Beth will discuss interim findings from her study about access to elite Mathematics higher education in England. Her qualitative study focuses on elite Mathematics potential, disadvantage and selection. Interviews with students, school teachers, lecturers and others have shed light on these issues and their impact on different social and gender groups. Findings are relevant to understanding current patterns of participation and reflecting on the role and influence of elite universities in the education system.
 
**Date:** Thursday 20 March 2025, 13:00-14:00. 

**Location:** Huxley Building, Room 139.
:::


## Previous Talks


### Febrary 2025

**Speaker:** [Dr Emily Nordmann](https://www.emilynordmann.com/), School of Psychology and Neuroscience, University of Glasgow.

**Title:** The place and case for lectures (and lecture capture)

**Abstract:**  In this session I will discuss the evolution of research on lecture capture, from focusing on the links between recording live lectures and attendance, to the integration of using lecture recordings as a generic study skill, to the impact of recording on widening participation and inclusivity. I will argue that the experience of the pivot to online has shown that live, face-to-face lectures (with lecture capture) still have a place in higher education and that concerns about engagement must not be used to roll back the bare minimum of accessibility provision. Finally, I will discuss strategies and interventions for how to promote self-regulation and professionalism more generally.


### January 2025

**Speaker:** [Professor Elinor Jones](https://www.ucl.ac.uk/statistics/people/elinor-jones), Department of Statistical Science, University College London.

**Title:** Getting Started in Tertiary Education Research.

**Abstract:** With education-focused roles in Higher Education becoming more common, there is an increasing emphasis on education-related scholarship for promotion and academic advancement. In this presentation, I offer some practical tips on getting started, including discussing what counts as education research and whether it differs from scholarship.

Drawing on insights from the inaugural UK Conference on Teaching Statistics (UKCOTS), I will address common challenges, including navigating the education research literature and building effective networks. I conclude with a call to action: as statisticians (and mathematicians!), can we use our skills to improve the quality and perceptions of education research not only in mathematics, but in other disciplines too?


### December 2024 

**Speaker:** [Professor Hector Keun](https://profiles.imperial.ac.uk/h.keun), Department of Surgery and Cancer, Imperial College London.

**Title:** Prior university as educational destiny in postgraduate taught course admissions at Imperial.

**Abstract:** As part of my role academic lead for postgraduate taught education in the Faculty of Medicine I have been exploring the factors which determine which applicants are successful when applying for PGT study at Imperial, in particular the importance of prior university.  My findings provide insights into how Imperial staff judge applications, what we think about undergraduate education at other universities and has relevance to theories of social reproduction.


<!--
### October 2024

**Speaker:** [Dr Ioanna Papatsouma](https://profiles.imperial.ac.uk/i.papatsouma) and [Dr Zak Varty](https://profiles.imperial.ac.uk/z.varty), Imperial College London.

**Title:** The impact of personal tutoring on students and staff.

**Abstract:** This session will explore the impact that personal tutoring can have on both students and staff. We will examine how personal tutoring influences academic success, student well-being, and staff-student relationships by summarising two studies covering the effectiveness of tutoring programs, their benefits and challenges for both students and staff. 

The session aims to spark a discussion on best practices and potential improvements in the tutoring system and how it might be optimised to ensure a positive, supportive and sustainable system for everyone involved.
-->

### March 2024

**Speaker:** [Professor Rachel Hilliam](https://www.open.ac.uk/people/rmh285), The Open University

**Title:** Should support for online students differ from ‘traditional’ support?

**Abstract:** Universities use a variety of ways to support their students and enhance their student experience. During covid it was often the support outside of traditional teaching sessions which were difficult for many places to replicate. The Open University has over 50 year experience of teaching and supporting students who learn online and at a distance. In particular the School of Mathematics and Statistics has for many years provided innovative ways of supporting students outside the ‘classroom’ environment was therefore well prepared to support students during the COVID-19 pandemic.

This talk will outline some of the forms of support which are offered to students in the School of Mathematics and Statistics  such as online forums to help students with module choice and taster resources including diagnostic quizzes for students to self-assess their readiness to study individual modules and receive targeted support. Since 2017, these resources, and more, have been incorporated into a multi-functional student-facing website. The website enables all units, both academic and non-academic, to provide consistent academic, pastoral and social support to students studying mathematics and statistics modules online. Analysis will be presented on how both staff and students use the site. 

A particular focus of this talk will explain how the website mirrors the different stages of a student’s journey, providing a one-stop shop for students to self-serve and obtain appropriate support at each point in their own student lifecycle.


### January 2024

**Speaker:** [Dr Paul Northrop](https://www.ucl.ac.uk/statistics/people/paulnorthrop), University College London. 

**Title:** Connecting students with statistical research 

**Abstract:** I describe one of the research-based learning exercises initiated by the Department of Statistical Science at UCL. First-year undergraduate students are put into groups of five or six people and assigned a statistical research paper to read. Their task is to prepare, and submit for formative assessment, a short report that communicates the key themes of the paper to a non-specialist audience. To help them, they conduct a one-hour interview with an author of the paper. We reflect on the experience of running this assessment over the past 9 years. Feedback from students and staff has mostly been very positive, despite the considerable challenges that this type of assessment poses to students at such an early stage of their studies. 
